In [1]:
import openpyxl
from pathlib import Path
import pandas as pd

In [3]:
to_load = Path("C:\\Users\\fontanesio\\PROMETEIA SPA\\Test - General\\test_2.xlsx")

In [5]:
s1 = pd.read_excel(to_load, sheet_name="S1")
s1

   IDX NOME COGNOME RESIDENZA
0    0    A      AA        MO
1    1    B      BB        MI
2    2    C      CC        PA
3    3    D      DD        PA
4    4    E      EE        RM

In [6]:
s2 = pd.read_excel(to_load, sheet_name="S2")
s2

   IDX       ATTR  VALORE
0    0       NOME    OTTO
1    0  RESIDENZA      BO
2    3    COGNOME  BARILE

In [7]:
def update_value(df_to_update, data):
    print("..updating..\nKEYS : IDX = {}, ATTR = {}\tOLD = {}\tNEW = {}".format(data.IDX, data.ATTR, df_to_update.loc[data.IDX, data.ATTR], data.VALORE))
    df_to_update.loc[data.IDX, data.ATTR] = data.VALORE
    return None

s2.apply(lambda x: update_value(df_to_update=s1, data=x), axis=1)

..updating..
KEYS : IDX = 0, ATTR = NOME	OLD = A	NEW = OTTO
..updating..
KEYS : IDX = 0, ATTR = RESIDENZA	OLD = MO	NEW = BO
..updating..
KEYS : IDX = 3, ATTR = COGNOME	OLD = DD	NEW = BARILE

0    None
1    None
2    None
dtype: object

In [8]:
s1

   IDX  NOME COGNOME RESIDENZA
0    0  OTTO      AA        BO
1    1     B      BB        MI
2    2     C      CC        PA
3    3     D  BARILE        PA
4    4     E      EE        RM