In [14]:
import pandas as pd
from pandas import ExcelWriter
from pathlib import Path

In [16]:
input_path = Path("C:\\Users\\fontanesio\\Documents\\pythonScripts\\progetti\\personali\\LogPPT-master\\tmp\\test.xlxs")
writer = ExcelWriter(input_path)
def save_xls(df:pd.DataFrame, writer:ExcelWriter, key:str, close:bool=False) -> None:
    """
    Save a dictionary of dataframes to an excel file, 
    with each dataframe as a separate page
    :param df: pd.DataFrame or pd.series to export
    :param writer: excel writer
    :param key: sheet name
    """
    df.to_excel(writer, sheet_name=key)
    if close:
        writer.save()
    return None

In [9]:
save_xls(dd[dd.TIPO=="PZ"], writer, key="PZ")

In [11]:
dd.groupby("TIPO").apply(lambda d: print(d.name))

BND
CSH
DER
EQY
FND
GP
PZ

Empty DataFrame
Columns: []
Index: []

In [17]:
input_path = Path("C:\\Users\\fontanesio\\Documents\\pythonScripts\\progetti\\personali\\LogPPT-master\\tmp\\test.xlxs")
writer = ExcelWriter(input_path)

dd = pd.read_csv(Path("C:\\Users\\fontanesio\\Documents\\CLIENTI\\BL\\tmp\\risorseADV_20231013\\ini\\catalogoTitoli.csv"), sep=";")
dd.groupby("TIPO").apply(lambda d: save_xls(d, writer, key=d.name))

c:\Users\fontanesio\AppData\Local\Programs\Python\Python37\lib\site-packages\IPython\core\interactiveshell.py:3146: DtypeWarning: Columns (21) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

Empty DataFrame
Columns: []
Index: []

In [19]:
writer.save()